//unused

#undef Box NULL
#undef Ellipse NULL
#undef Cells NULL
#undef Plasm NULL
#undef LGradient NULL
#undef ChessField NULL
#undef AddStars NULL
#undef TTwirl NULL
#undef TLenz NULL
#undef TWaves NULL
#undef SetPhase NULL
#undef AnimaSin NULL
#undef QCRotate NULL
#undef Flat NULL
#undef PointLight NULL
#undef MultiTexture NULL
#undef RWave NULL
#undef Fog NULL
#undef DisableFog NULL
#undef ScreenToTexture NULL
#undef Desaturate NULL
#undef CopyToAlpha NULL
#undef RGBDisplace NULL
#undef ShBlur NULL
#undef Julia NULL
#undef SinColor NULL
#undef Palette NULL
#undef AdjustColor NULL
#undef Sharp NULL
#undef CEmboss NULL
#undef TextureQuad NULL
#undef ClearRGB NULL
#undef MpGrad NULL
#undef InvertAlpha NULL
#undef ModCopyToAlphaFromTexture NULL
#undef RDisplace NULL
#undef CopyAlphaFromTexture NULL
#undef LoadTexture NULL
#undef Glow NULL
#undef SDisplace NULL
#undef AtoRGB NULL
#undef AnimaPow3 NULL
#undef AnimaPow2 NULL
#undef Anima4SQRT NULL
#undef Crossfade NULL
#undef ShowVB NULL
#undef ParticleArray NULL
#undef AnimaRandom NULL
#undef AddToVB NULL
#undef CleanVB NULL
#undef AnimaClampMax NULL
#undef AnimaClampMin NULL
#undef AnimaClampMode NULL
#undef Anima2SQRT NULL
#undef SetMaxRecurrenceLevel NULL
#undef LoadMesh NULL
#undef ShowMesh NULL
#undef TextBlock NULL
#undef LoadText NULL
#undef Point NULL
#undef Curve NULL
#undef Perlin NULL
#undef StoreCurve NULL
#undef AnimaSpline NULL
#undef TrackXYZ NULL
#undef Spline2Camera NULL
#undef Spline1Camera NULL
#undef TimeLine NULL
#undef OverrideTM NULL
#undef LoadXM NULL
#undef EndTimeLine NULL
#undef PartOut NULL
#undef SetShader NULL
#undef RemoveSelection NULL
#undef InvertSelection NULL
#undef Skew NULL
#undef Halftone NULL
#undef XYZtoRGB NULL
#undef StoreCamera NULL
#undef Shadow NULL
#undef ReflectCamY NULL
#undef Posterize NULL
#undef CopyStartScr NULL
#undef CopyUVtoUV1 NULL
#undef XYZtoUV NULL
#undef SXYtoUV NULL
#undef AddPerlinH NULL
#undef CompileShaderToSlot NULL
#undef IrregularGrid NULL
#undef RotateCamera NULL
#undef ShowVBsMap3D NULL
#undef CopyObjToPosBuf NULL
#undef XYZbyCurve NULL
#undef SetVBsHead NULL
#undef Tree NULL
#undef LoftW NULL
#undef LoftY NULL
#undef LoadWave NULL
#undef TRotate NULL
#undef TZoom NULL
#undef SetTextureForVS NULL
#undef ShowObjFromTexture NULL
#undef Animate NULL
#undef Key NULL
#undef keyLoop NULL
#undef keyLoopEnd NULL
#undef ShowVBsL NULL
#undef IndexedIoIsolated NULL
#undef texToRam NULL
#undef MakeInstTable NULL
#undef SetScatter NULL


