#define Box NULL
#define Ellipse NULL
#define Cells NULL
#define Plasm NULL
#define LGradient NULL
#define ChessField NULL
#define AddStars NULL
#define TTwirl NULL
#define TLenz NULL
#define TWaves NULL
#define SetPhase NULL
#define AnimaSin NULL
#define QCRotate NULL
#define Flat NULL
#define PointLight NULL
#define MultiTexture NULL
#define RWave NULL
#define Fog NULL
#define DisableFog NULL
#define ScreenToTexture NULL
#define Desaturate NULL
#define CopyToAlpha NULL
#define RGBDisplace NULL
#define ShBlur NULL
#define Julia NULL
#define SinColor NULL
#define Palette NULL
#define AdjustColor NULL
#define Sharp NULL
#define CEmboss NULL
#define TextureQuad NULL
#define ClearRGB NULL
#define MpGrad NULL
#define InvertAlpha NULL
#define ModCopyToAlphaFromTexture NULL
#define RDisplace NULL
#define CopyAlphaFromTexture NULL
#define LoadTexture NULL
#define Glow NULL
#define SDisplace NULL
#define AtoRGB NULL
#define AnimaPow3 NULL
#define AnimaPow2 NULL
#define Anima4SQRT NULL
#define Crossfade NULL
#define ShowVB NULL
#define ParticleArray NULL
#define AnimaRandom NULL
#define AddToVB NULL
#define CleanVB NULL
#define AnimaClampMax NULL
#define AnimaClampMin NULL
#define AnimaClampMode NULL
#define Anima2SQRT NULL
#define SetMaxRecurrenceLevel NULL
#define LoadMesh NULL
#define ShowMesh NULL
#define TextBlock NULL
#define LoadText NULL
#define Point NULL
#define Curve NULL
#define Perlin NULL
#define StoreCurve NULL
#define AnimaSpline NULL
#define TrackXYZ NULL
#define Spline2Camera NULL
#define Spline1Camera NULL
#define TimeLine NULL
#define OverrideTM NULL
#define LoadXM NULL
#define EndTimeLine NULL
#define PartOut NULL
#define SetShader NULL
#define RemoveSelection NULL
#define InvertSelection NULL
#define Skew NULL
#define Halftone NULL
#define XYZtoRGB NULL
#define StoreCamera NULL
#define Shadow NULL
#define ReflectCamY NULL
#define Posterize NULL
#define CopyStartScr NULL
#define CopyUVtoUV1 NULL
#define XYZtoUV NULL
#define SXYtoUV NULL
#define AddPerlinH NULL
#define CompileShaderToSlot NULL
#define IrregularGrid NULL
#define RotateCamera NULL
#define ShowVBsMap3D NULL
#define CopyObjToPosBuf NULL
#define XYZbyCurve NULL
#define SetVBsHead NULL
#define Tree NULL
#define LoftW NULL
#define LoftY NULL
#define LoadWave NULL
#define TRotate NULL
#define TZoom NULL
#define SetTextureForVS NULL
#define ShowObjFromTexture NULL
#define Animate NULL
#define Key NULL
#define keyLoop NULL
#define keyLoopEnd NULL
#define ShowVBsL NULL
#define IndexedIoIsolated NULL
#define texToRam NULL
#define MakeInstTable NULL
#define SetScatter NULL
